# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# markdownlint

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=10000]
      - id: check-ast
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      # - id: check-json
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black

  - repo: https://github.com/hadolint/hadolint
    rev: v2.8.0
    hooks:
      - id: hadolint
        args: [--ignore, DL3008] # prefer not to pin apt packages versions

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.3.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.5.1" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        exclude: "^perf/bench/dummy/.+$|^semgrep/tests/e2e/rules/.+$|^.+/poetry.lock$"
